### ISSUE TITLE
Examples on docs site are unreadable

### ISSUE THREAD

**Issue by Flascher** [adaltas/node-csv-docs#11]
The examples on the docs site ([here, as well as the other csv submodules examples](http://csv.adaltas.com/transform/examples/)) show the syntax highlighting briefly after page load, and then the text color seems to be overridden to the same color as the background (both are #333).

<img width="763" alt="screen shot 2017-11-26 at 1 35 16 pm" src="https://user-images.githubusercontent.com/2762315/33243603-eaab24b2-d2ae-11e7-8703-578388b45f4d.png">

In the attached screenshot you can see that the text is in fact there, but not rendered with the proper syntax highlighting.

**Comment by wdavidw** [comment]
Please clarify, I have no problem accessing the sample pages, for exemple the [parse examples](http://csv.adaltas.com/parse/examples/).

**Comment by wdavidw** [comment]
I've tested with firefox and chrome.

**Comment by Flascher** [comment]
My apologies. I should have tested a different browser myself. This occurs for me in Chrome, but not in Safari. It appears as though an extension may be causing this issue, though I'm not sure which one yet. I'll close this issue :)
