### ISSUE TITLE
No examples on how to parse csv files.

### ISSUE THREAD

**Issue by mjcorts001** [adaltas/node-csv-docs#36]
Most of the example are parsing hardcoded csv strings

[Docs](https://csv.js.org/parse/examples/)

**Comment by cefn** [comment]
I arrived at the same conclusion. Couldn't find an example, even on the page that includes the quote below. The example does no such thing. It actually uses https://csv.js.org/generate/ instead and in my case I would like reference code for loading my own CSV file as promised in the description.

```
The pipe example reads a file, parses its content, transforms it and print the result to the standard output.
```
https://csv.js.org/parse/recipies/stream_pipe/

**Comment by wdavidw** [comment]
@mjcorts001 The majority of the examples illustrate a specific usage such as the behavior of an option. The objective is to maximize the simplicity of the code to illustrate only one feature. This is why we are passing strings. In production, when handling large volume of data, only the stream API is recommended: https://csv.js.org/parse/api/

@cefn The library doesn't parse files, it parses bytes. Whether those bytes are coming from a file, a network connection or a string is up to you. When dealing with streams of bytes, such as when reading a file, Node.js has an interface which standardize stream handling: https://nodejs.org/api/stream.html.

Feel free to enrich the [file interaction](https://csv.js.org/parse/recipies/file_interaction/) recipe with the usage of `fs.createReadStream(...).pipe(...)`
