### ISSUE TITLE
Errors in 'File system interaction' page for csv-parse

### ISSUE THREAD

**Issue by enumjorge** [adaltas/node-csv-docs#43]
There's a couple of errors in the sync example at the bottom of this page: https://csv.js.org/parse/recipies/file_interaction/

The path to the parse module is incorrect our outdated. `const parse = require('csv-parse/lib/parse')` should changed to `const parse = require('csv-parse/lib/sync')'.

The for loop should use 'for of' instead of 'for in' otherwise, you'll only get the indices of records written to the console: `for(let record in records)`.

**Comment by wdavidw** [comment]
Thank you, it also seems like we should use `require('fs').promises` in the second code block.
