### ISSUE TITLE
Semicolon needed in the async iterator example code

### ISSUE THREAD

**Issue by kurtishouser** [adaltas/node-csv-docs#78]
The example code on https://github.com/adaltas/node-csv-docs/blob/master/src/md/parse/api/async_iterator.md needs a semicolon after `const parse = require('csv-parse')`. It's followed by an IIFE. I ran the code and received the following error:
```
filepath/async_iterator.js:28
})();
  ^

TypeError: require(...)(...) is not a function
```

**Comment by wdavidw** [comment]
Thanks, I fixed it.
