### ISSUE TITLE
browser import paths do not exist

### ISSUE THREAD

**Issue by cainlevy** [adaltas/node-csv-docs#98]
The browser import paths mentioned in https://github.com/adaltas/node-csv-docs/blob/master/src/md/parse/distributions/browser_esm.md#usage do not exist in the current version of csv-parse. The closest I can find is `csv-parse/dist/esm`, which does seem to work.

**Comment by wdavidw** [comment]
Thank you for reporting, doc is updated for every package.

**Comment by cainlevy** [comment]
I observed the path as `csv-parse/dist/esm` instead of `csv-parse/browser/esm`. Have I overlooked something? Is the `browser` directory present in other packages?

**Comment by wdavidw** [comment]
if you manually place the file in your web server, then the path is entirely up to the user. For example if you map the HTTP routes `csv-parse/*` to the folder `node_modules/csv-parse`, you end up with `csv-parse/dist/esm/index.js`. If using webpack, then `package.json` export field is used and it declare `csv-parse/browser/esm`

**Comment by cainlevy** [comment]
Wow. That's a lot to support all at once.

Just to make it more confounding, support for `exports` in TypeScript appears to have landed only a few months ago.

**Comment by wdavidw** [comment]
Right, I forgot TypeScript in the list! The situation makes the doc complex to read, I spent a lot of time thinking about its organization and I wish it would have been much easier. This is also the reason why we have a lot of [demos](https://github.com/adaltas/node-csv/tree/master/demo). Demos also include TypeScript and it seems to work in all the scenario.
